{{- if and .Values.customRootCA.crt (not .Values.customRootCA.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synaplan.customRootCA.secretName" . }}
  labels:
    {{- include "synaplan.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.customRootCA.crt | nindent 4 }}
{{- end }}
