{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synaplan.fullname" . }}-redis
  labels:
    {{- include "synaplan.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "synaplan.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
