"""
Embedding backend for Triton Inference Server.

Provides dense embedding inference using HuggingFace transformers.
Designed for models like BAAI/bge-m3 that produce fixed-dimension
dense embeddings from text input.

Configuration is read from model.json (merged from embeddingDefaults +
per-model overrides by the Helm chart).

IMPORTANT: This backend is NOT thread-safe — it holds a single model
in memory.  The config.pbtxt generated by the Helm chart sets
``instance_group [{ count: 1, kind: KIND_CPU }]`` which ensures Triton
runs exactly one instance.  Do not increase the count without adding
proper synchronisation.
"""

import json
import os
import traceback

import numpy as np
import triton_python_backend_utils as pb_utils


class TritonPythonModel:

    def initialize(self, args):
        model_dir = args["model_repository"]
        version = args["model_version"]
        config_path = os.path.join(model_dir, version, "model.json")

        print(f"[embedding-backend] Loading config from {config_path}...", flush=True)
        with open(config_path) as f:
            self.config = json.load(f)

        model_path = self.config["model"]
        dtype = self.config.get("dtype", "float16")

        print(
            f"[embedding-backend] Loading model from {model_path} (dtype={dtype})...",
            flush=True,
        )

        import torch
        from transformers import AutoModel, AutoTokenizer

        dtype_map = {
            "float32": torch.float32,
            "float16": torch.float16,
            "bfloat16": torch.bfloat16,
        }
        torch_dtype = dtype_map.get(dtype, torch.float16)

        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path,
            local_files_only=True,
            trust_remote_code=True,
        )

        self.model = AutoModel.from_pretrained(
            model_path,
            local_files_only=True,
            trust_remote_code=True,
            torch_dtype=torch_dtype,
        )
        self.model.eval()
        self._torch_dtype = torch_dtype

        print("[embedding-backend] Model loaded successfully.", flush=True)

    def execute(self, requests):
        import torch

        responses = []
        for request in requests:
            try:
                text_input = pb_utils.get_input_tensor_by_name(request, "text_input")
                if text_input is None:
                    raise ValueError("Input tensor 'text_input' not found.")

                raw = text_input.as_numpy()[0]
                if isinstance(raw, bytes):
                    text = raw.decode("utf-8")
                else:
                    text = str(raw)

                # Tokenize
                inputs = self.tokenizer(
                    text,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=8192,
                )

                # Forward pass
                with torch.no_grad():
                    outputs = self.model(**inputs)

                # Mean pooling over token embeddings (mask-aware)
                token_embeddings = outputs.last_hidden_state
                attention_mask = inputs["attention_mask"].unsqueeze(-1)
                masked = token_embeddings * attention_mask.to(token_embeddings.dtype)
                summed = masked.sum(dim=1)
                counts = attention_mask.to(token_embeddings.dtype).sum(dim=1)
                mean_pooled = summed / counts

                # L2 normalize
                embedding = torch.nn.functional.normalize(mean_pooled, p=2, dim=1)

                # Convert to float32 numpy for output
                embedding_np = embedding.cpu().float().numpy().flatten()

                responses.append(
                    pb_utils.InferenceResponse(
                        output_tensors=[
                            pb_utils.Tensor("embedding", embedding_np)
                        ]
                    )
                )

            except Exception as e:
                print(f"[embedding-backend] Error: {e}", flush=True)
                print(traceback.format_exc(), flush=True)
                responses.append(
                    pb_utils.InferenceResponse(
                        output_tensors=[],
                        error=pb_utils.TritonError(str(e)),
                    )
                )

        return responses

    def finalize(self):
        print("[embedding-backend] Finalizing...", flush=True)
